# Use the official Node.js image as a base image
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Copy the .env file
COPY .env .env

# Expose the port the app runs on
EXPOSE 1337

# Set environment variables from .env file
ENV NODE_ENV=production
ENV URL=https://cei-web-portal-strapi-latest.onrender.com

# Start the Strapi server
CMD ["sh", "-c", "npm start"]
